### PR TITLE
tiledbsoma 1.5.0rc1

### PR DESCRIPTION
**Pull request by johnkerl**
Following https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases

### CODE REVIEW

**Review by jdblischak — APPROVED** [review]

**Review by jdblischak — CHANGES_REQUESTED** [review]

**Comment by johnkerl** [comment]
Blocked on https://github.com/conda-forge/tiledb-py-feedstock/pull/181

**Review by jdblischak — APPROVED** [review]

**Comment by johnkerl** [comment]
New error in CI:
```
package tiledbsoma-py-1.5.0rc1-py37h158d4c2_0 requires scanpy 1.9.*, but none of the providers can be installed
```

**Comment by johnkerl** [comment]
Weird: https://anaconda.org/conda-forge/scanpy/files has 1.9.5 ... 🤔 ...

**Comment by jdblischak** [comment]
scanpy 1.9.4 dropped support for Python 3.7 (https://github.com/conda-forge/scanpy-feedstock/pull/8). So the question is: why can't it install scanpy 1.9.1, 1.9.2, or 1.9.3?

**Comment by jdblischak** [comment]
Ah, I know why! The py37 conda binary is created by the fork TileDB-Inc/tiledb-py-feedstock

https://github.com/TileDB-Inc/tiledb-py-feedstock/tree/build-linux-64-py37

I have a job that runs every 6 hours. It checks conda-forge/tiledb-py-feedstock and then updates TileDB-Inc/tiledb-py-feedstock

https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/workflows/linux-py37.yml

It last ran 5 hours, and the update commit landed an hour ago. I just manually triggered the job

https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/6355570813

**Comment by jdblischak** [comment]
What to watch:

https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=35299&view=results
https://anaconda.org/tiledb/tiledb-py/files

**Comment by jdblischak** [comment]
Uploaded https://anaconda.org/tiledb/tiledb-py/files?version=0.23.1

**Pull request merged**
