### PR TITLE
tiledbsoma 1.9.1 pre-check

### PR DESCRIPTION
**Pull request by johnkerl**
Following our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases)

### CODE REVIEW

**Review by jdblischak — CHANGES_REQUESTED** [review]
tiledb pin needs bumped to 2.21

**Comment by johnkerl** [comment]
@jdblischak derp, I failed to apply the patch from #110 :|

**Review by jdblischak — APPROVED** [review]
pre-check approved

**Review by jdblischak — CHANGES_REQUESTED** [review]
Wait a second. It looks like you deleted all the CI files. Can you try rerendering again?

**Comment by johnkerl** [comment]
Sorry I was midway through a rerender & tabbed away -- just pushed the last commit ...

**Review by jdblischak — APPROVED** [review]

**Comment by johnkerl** [comment]
Closing per our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases)

**Pull request closed without merging**
