### PR TITLE
Depend on core >= 2.15.2, < 2.16

### PR DESCRIPTION
**Pull request by johnkerl**
As in https://github.com/single-cell-data/TileDB-SOMA/pull/1296 and https://github.com/single-cell-data/TileDB-SOMA/pull/1303, for the same reasons already narrated there.

### CODE REVIEW

**Review by Shelnutt2 — CHANGES_REQUESTED** [review]
Pinning needs to have an upperbound to prevent bringing in 2.16 or newer. Something like `tiledb >=2.15.1,<2.16` (taken from https://github.com/conda-forge/tiledb-py-feedstock/blob/f153315c81da2ed5f2d89a968c94892aca4b0bde/recipe/meta.yaml#L35)

**Comment by jdblischak** [comment]
Since you are changing the recipe but not the package version, now is when you bump the build number from `0` to `1`

**Comment by johnkerl** [comment]
@jdblischak @Shelnutt2 thank you both for teaching me things!

That said, I'm going to hold off b/c TileDB-Py 0.21.3 with core 2.15.2 is just around the corner:
https://github.com/TileDB-Inc/TileDB-Py/pull/1754

**Comment by johnkerl** [comment]
Folding this into #18

**Pull request closed without merging**
