### PR TITLE
tiledbsoma 1.12.2

### PR DESCRIPTION
**Pull request by johnkerl**
Following our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases)

### CODE REVIEW

**Comment by johnkerl** [comment]
CI fail:

```
Could not solve for environment specs
The following packages are incompatible
├─ aws-crt-cpp 0.27.1.* h93f15ff_1 is requested and can be installed;
└─ libtiledbsoma 1.12.2.* h4074421_0 is not installable because it requires
   └─ tiledb >=2.24.1,<2.25.0a0 , which requires
      └─ aws-crt-cpp >=0.26.12,<0.26.13.0a0 , which conflicts with any installable versions previously reported.
```

-- I am looking at https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/171 which seems related ...

**Comment by johnkerl** [comment]
I see history
https://github.com/conda-forge/tiledb-feedstock/commits/main/recipe/meta.yaml
pointing to
https://github.com/conda-forge/tiledb-feedstock/commit/55590d9692bfc38acbdb8784cb9e625c99f8ebf7
on
https://github.com/conda-forge/tiledb-feedstock/pull/308
just yesterday.

That has build number 3
[https://github.com/conda-forge/tiledb-feedstock/commit/55590d9692bfc38acbdb8784cb9e625c99f8ebf7#diff-f3725a55bf339595bf8[…]0c205442021f29c06eea9aR23](https://github.com/conda-forge/tiledb-feedstock/commit/55590d9692bfc38acbdb8784cb9e625c99f8ebf7#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR23)
and version 2.24.1
[https://github.com/conda-forge/tiledb-feedstock/commit/55590d9692bfc38acbdb8784cb9e625c99f8ebf7#diff-f3725a55bf339595bf8[…]10c205442021f29c06eea9aR2](https://github.com/conda-forge/tiledb-feedstock/commit/55590d9692bfc38acbdb8784cb9e625c99f8ebf7#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR2)

However, at
https://anaconda.org/conda-forge/tiledb/files
I only currently see build number 2 latest.

It turns out we had an Azure DevOps run failure for
https://github.com/conda-forge/tiledb-feedstock/pull/308
-- I'll work with @ihnorton @KiterLuc to see if we can resolve that ...

**Comment by johnkerl** [comment]
Update: system-wide Azure issue:
https://github.com/conda-forge/status/issues/181

**Comment by johnkerl** [comment]
Azure log:
https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40188&view=logs&j=516f237f-98f1-50a4-0946-c43fe5437b81&t=19870002-9ea0-5c64-a2c3-e2872fb3f101

```
binstar_client.errors.BinstarError: ('Storage requirements exceeded (3221225472 bytes).', 402)
```

**Comment by jdblischak** [comment]
Superseded by #184

**Comment by jdblischak** [comment]
Post-mortem thoughts: @johnkerl I think you made the correct diagnosis above in https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/181#issuecomment-2211106638. You just had the very unfortunate luck of Azure issues that compounded the problem.

There were recently back-to-back aws-crt-cpp migrations, which was guaranteed to cause some temporary chaos. Looks like things have settled down now

https://conda-forge.org/status/migration/aws_crt_cpp0271
https://conda-forge.org/status/migration/aws_crt_cpp0272

**Pull request closed without merging**
