### PR TITLE
tiledbsoma 1.4.1

### PR DESCRIPTION
**Pull request by johnkerl**

### CODE REVIEW

**Comment by johnkerl** [comment]
Render info:

```
$ conda smithy rerender --commit auto
...
INFO:conda_smithy.configure_feedstock:Re-rendered with conda-build 3.25.0, conda-smithy 3.24.1, and conda-forge-pinning 2023.08.15.13.25.15
INFO:conda_smithy.configure_feedstock:No changes made. This feedstock is up-to-date.
```

**Comment by jdblischak** [comment]
Two questions:

1. Are we skipping the [test PR](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases#branchtag-mechanics) because this is patch version update?
2. Unless this is super urgent, what about rebasing this on top of PR #38? Merging them together would save CI time overall (and fewer conda artifacts to store)

**Comment by johnkerl** [comment]
> Are we skipping the [test PR](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases#branchtag-mechanics) because this is patch version update?

Yes, there was so very little to possibly go wrong

> Unless this is super urgent

@Shelnutt2 wanted this sooner than latter

**Comment by jdblischak** [comment]
It looks the R package version wasn't bumped to 1.4.1. It's still at 1.4.0, and the conda recipe now uses a single version for libtiledbsoma and the Python/R clients

https://github.com/single-cell-data/TileDB-SOMA/blob/1.4.1/apis/r/DESCRIPTION#L7

**Comment by johnkerl** [comment]
@jdblischak I'll do a 1.4.2 with a test PR then.

**Comment by jdblischak** [comment]
> I'll do a 1.4.2 with a test PR then.

I wasn't arguing for a test PR (that is totally your decision). I was only requesting either 1) the R version be synced, or 2) we decouple the R version again in the conda recipe

**Comment by johnkerl** [comment]
> I wasn't arguing for a test PR (that is totally your decision)
We are on the same page :) 

> I was only requesting either 1) the R version be synced, or 2) we decouple the R version again in the conda recipe

As a team we have decided to forevermore sync all language versions in this package (so option 2 is out). And tags are immutable. And GitHub tag 1.4.1 has 1.4.0 in `apis/r/DESCRIPTION`. So this means necessarily a 1.4.2 (option 1).

**Comment by johnkerl** [comment]
@jdblischak 
https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases/_compare/bb544e2d017bb8fd7fad2e8afa6cdbc49da50c29...3c5ce25f805678b139723508e8100d0e23497862

**Pull request closed without merging**
