### PR TITLE
Pre-tag check for TileDB-SOMA 1.2.4

### PR DESCRIPTION
**Pull request by johnkerl**
This is _not_ the release PR -- this is a pre-release check PR following our standard procedure at
https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases

### CODE REVIEW

**Comment by jdblischak** [comment]
Do you still need to update the pins for `tiledb` and `tiledb-py` like you had done in PR #21?

**Comment by johnkerl** [comment]
Good call -- thanks @jdblischak !

**Comment by jdblischak** [comment]
The linux build failed with a conda solver error when creating the environment to build the Python env. It's the same solver error we battled in #20 that only affects Python 3.10. I was hoping it was only transient. I had to switch from testing Python 3.10 to Python 3.9 last week when testing PR #22 (https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/22/commits/75120f788df8fb9d1477a96672a30364ee37146d)

**Comment by jdblischak** [comment]
Also, I recommend rerendering to see if that helps `conda smithy rerender --commit auto`

**Pull request closed without merging**
