### PR TITLE
tiledbsoma release 1.4.3

### PR DESCRIPTION
**Pull request by johnkerl**
Following our established procedure
https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases

### CODE REVIEW

**Review by jdblischak — APPROVED** [review]

**Comment by johnkerl** [comment]
https://github.com/pulls?q=is%3Apr+author%3Ajohnkerl+archived%3Afalse+sort%3Aupdated-desc
running jobs

**Comment by johnkerl** [comment]
https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=34374&view=results

**Comment by jdblischak** [comment]
There was a spurious HTTP failure in the osx build of the merged commit. We can restart it [here](https://github.com/TileDB-Inc/tiledbsoma-feedstock/runs/16019645439)

**Comment by johnkerl** [comment]
[sc-33078]

**Pull request merged**
