### PR TITLE
Pre-release test for TileDB-SOMA 1.2.3

### PR DESCRIPTION
**Pull request by johnkerl**
Not to be merged. Just a check for "is the putative TileDB-SOMA 1.2.3 Conda-CI green?".

### CODE REVIEW

**Comment by johnkerl** [comment]
I don't know why this is failing:
* https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/18
* https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/18/checks?check_run_id=13182539344
* https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=31883&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

```
package libtiledbsoma-1.2.2-h25619bb_0 requires tiledb >=2.15.2,<2.16, but none of the providers can be installed
```

given that at
https://anaconda.org/conda-forge/tiledb/labels
https://anaconda.org/conda-forge/tiledb/files
we do have 2.15.2 available ... :thinking_face:

**Comment by jdblischak** [comment]
I don't think it's related to the test changes in this PR. I just synced "main" on my fork of the feedstock, and it failed with the same error

https://github.com/jdblischak/tiledbsoma-feedstock/tree/bb3fbeb622d88809cf20bc8b58c3a480803334c7
https://dev.azure.com/jdblischak/feedstock-builds/_build/results?buildId=248&view=results

**Comment by jdblischak** [comment]
I'm having trouble reproducing the solver error locally on Ubuntu. In the CI builds, libtiledbsoma builds fine, but then fails to solve the env once it tries to build the Python client:

```
mamba create --dry-run -n test-soma \
  --override-channels -c conda-forge -c tiledb \
  libtiledbsoma=1.2.2=h25619bb_0
##   + libtiledbsoma           1.2.2  h25619bb_0        tiledb/linux-64           246kB
##   + tiledb                 2.15.2  heaeb544_0        conda-forge/linux-64        6MB

mamba create --dry-run -n test-soma \
  --override-channels -c conda-forge -c tiledb \
  libtiledbsoma=1.2.2=h25619bb_0 \
  python=3.10 \
  tiledb-py \
  tiledbsoma-py
##   + libtiledbsoma              1.2.2  h25619bb_0               tiledb/linux-64           246kB
##   + tiledb                    2.15.2  heaeb544_0               conda-forge/linux-64        6MB
##   + tiledb-py                 0.21.3  py310hf537494_0          conda-forge/linux-64        1MB
##   + tiledbsoma-py              1.2.2  py310h40e830b_0          tiledb/linux-64           278kB
```

**Comment by johnkerl** [comment]
Pre-release green CI verified; closing as intended.

**Comment by jdblischak** [comment]
The nightly binaries from #19 have already been uploaded, so you could even locally install the latest version built from "main"

https://anaconda.org/tiledb/libtiledbsoma/files?channel=nightlies
https://anaconda.org/tiledb/tiledbsoma-py/files?channel=nightlies

You can install them locally by running the following:

```sh
mamba create -n soma-nightly --override-channels \
  -c conda-forge -c "tiledb/label/nightlies" -c tiledb \
  tiledbsoma-py="*20230503"
conda activate soma-nightly
conda list soma
## libtiledbsoma             1.2.2.dev20230503      hc1eed26_0    tiledb/label/nightlies
## somacore                  1.0.0              pyh4471522_1    tiledb
## tiledbsoma-py             1.2.2.dev20230503 py310h7717f27_0    tiledb/label/nightlies
python -c "import tiledbsoma; print(tiledbsoma.pytiledbsoma.version())"
## libtiledb=2.15.2
```

**Comment by johnkerl** [comment]
Actually there was contentful stuff on here -- this PR was conflating two things:

* Pre-release test;
* It folded in #17 

@Shelnutt2 @jdblischak would it be better to re-open #17 and get it merged, then do the 1.2.3 release per se? Or, would it be better to fold the #17 content into the (upcoming) actually-release-1.2.3 PR?

**Comment by jdblischak** [comment]
> would it be better to re-open https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/17 and get it merged, then do the 1.2.3 release per se?

If the updated version restriction applies to 1.2.2, then I think it makes sense to merge that first (just bump the build number), and then later update to 1.2.3 (and return the build number to 0).

**Comment by johnkerl** [comment]
Ah of course @jdblischak ; I should have looked at it that way.

The restriction on TileDB core >=2.15.2 and TileDB-Py >= 0.21.3 is specifically for TileDB-SOMA 1.2.3. So, doing separate PRs would not make sense after all.

**Pull request closed without merging**
