### PR TITLE
tiledbsoma 1.8.1 pre-check

### PR DESCRIPTION
**Pull request by johnkerl**
Following our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases)

### CODE REVIEW

**Comment by johnkerl** [comment]
[sc-43258]

**Comment by johnkerl** [comment]
This is failing for the same reason as #103

**Comment by jdblischak** [comment]
Doesn't tiledbsoma 1.8.1 require somacore 1.0.9 like in #98? Looking at the commit this is using, it includes the previous commit to bump somacore to 1.0.9

https://github.com/single-cell-data/TileDB-SOMA/commits/81a0f604860dafd147ced42d10134310332bb979/

**Comment by johnkerl** [comment]
@jdblischak good call, I'll merge #98 into here.

**Comment by johnkerl** [comment]
This draft pre-check PR has done its job per our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases); closing.

**Pull request closed without merging**
